// scripts/fetch-psgc.mjs
// One-shot data fetcher: pulls the PSGC (Philippine Standard Geographic
// Code) hierarchy from psgc.gitlab.io and emits a SQL migration that
// seeds ph_regions, ph_provinces, ph_cities, ph_barangays.
//
// Usage:  node scripts/fetch-psgc.mjs
// Output: supabase/migrations/20260502120500_psgc_seed.sql
//
// Requires: Node 18+ (for global fetch).

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const API = "https://psgc.gitlab.io/api";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = resolve(__dirname, "../supabase/migrations");
const MANILA_CITY_CODE = "133900000";

const sqlEscape = (s) =>
  s == null ? "NULL" : `'${String(s).replaceAll("'", "''")}'`;

const batchInsert = (table, columns, rows, chunk = 500) => {
  if (rows.length === 0) return "";
  let out = "";
  for (let i = 0; i < rows.length; i += chunk) {
    const slice = rows.slice(i, i + chunk);
    const values = slice
      .map((r) => `(${columns.map((c) => sqlEscape(r[c])).join(", ")})`)
      .join(",\n  ");
    out += `INSERT INTO ${table} (${columns.join(", ")}) VALUES\n  ${values}\nON CONFLICT (code) DO NOTHING;\n\n`;
  }
  return out;
};

async function fetchAll() {
  const fetchJson = async (url) => {
    const r = await fetch(url);
    if (!r.ok) throw new Error(`${url} -> ${r.status}`);
    return r.json();
  };
  console.log("Fetching regions...");
  const regions = await fetchJson(`${API}/regions/`);
  console.log(`  ${regions.length} regions`);
  console.log("Fetching provinces...");
  const provinces = await fetchJson(`${API}/provinces/`);
  console.log(`  ${provinces.length} provinces`);
  console.log("Fetching cities-municipalities...");
  const cities = await fetchJson(`${API}/cities-municipalities/`);
  console.log(`  ${cities.length} cities/municipalities`);
  console.log("Fetching barangays (this is the big one)...");
  const barangays = await fetchJson(`${API}/barangays/`);
  console.log(`  ${barangays.length} barangays`);
  return { regions, provinces, cities, barangays };
}

function transform({ regions, provinces, cities, barangays }) {
  //regions
  const rRows = regions.map((r) => ({ code: r.code, name: r.name }));

  //provinces
  const pRows = provinces.map((p) => ({
    code: p.code,
    region_code: p.regionCode,
    name: p.name,
  }));

  //cities — NCR ones have provinceCode === false
  const cityCodes = new Set();
  const cRows = cities.map((c) => {
    cityCodes.add(c.code);
    return {
      code: c.code,
      province_code: c.provinceCode || null,
      name: c.name,
    };
  });

  //barangays — resolve parent via cascade; redirect Manila sub-munis
  let skipped = 0;
  const bRows = [];
  for (const b of barangays) {
    let parent = b.cityCode || b.municipalityCode || b.subMunicipalityCode || null;
    if (!parent || !cityCodes.has(parent)) {
      //Manila sub-municipalities (codes 13390X000): redirect to Manila proper
      if (typeof parent === "string" && parent.startsWith("1339")) {
        parent = MANILA_CITY_CODE;
      } else {
        skipped++;
        continue;
      }
    }
    bRows.push({
      code: b.code,
      city_code: parent,
      name: b.name,
    });
  }
  console.log(`  resolved ${bRows.length} barangays, skipped ${skipped} (no parent in cities)`);
  return { rRows, pRows, cRows, bRows };
}

function header(filename, scope) {
  return (
    `-- supabase/migrations/${filename}\n` +
    `-- PSGC reference data — ${scope}.\n` +
    `-- Generated by scripts/fetch-psgc.mjs from https://psgc.gitlab.io/api/\n\n`
  );
}

function emit({ rRows, pRows, cRows, bRows }) {
  const files = [];

  //Part 1: schema alter + regions + provinces (tiny)
  {
    const fn = "20260502120500_psgc_alter_and_top.sql";
    let sql = header(fn, "alter ph_cities + regions + provinces");
    sql += "ALTER TABLE ph_cities ALTER COLUMN province_code DROP NOT NULL;\n\n";
    sql += `-- Regions: ${rRows.length}\n`;
    sql += batchInsert("ph_regions", ["code", "name"], rRows);
    sql += `-- Provinces: ${pRows.length}\n`;
    sql += batchInsert("ph_provinces", ["code", "region_code", "name"], pRows);
    files.push({ name: fn, sql });
  }

  //Part 2: cities (~1.6K, ~80KB)
  {
    const fn = "20260502120501_psgc_cities.sql";
    let sql = header(fn, "cities/municipalities");
    sql += `-- Cities/Municipalities: ${cRows.length}\n`;
    sql += batchInsert("ph_cities", ["code", "province_code", "name"], cRows);
    files.push({ name: fn, sql });
  }

  //Parts 3-5: barangays in three chunks
  const third = Math.ceil(bRows.length / 3);
  const chunks = [
    bRows.slice(0, third),
    bRows.slice(third, third * 2),
    bRows.slice(third * 2),
  ];
  chunks.forEach((chunk, idx) => {
    const fn = `2026050212050${2 + idx}_psgc_barangays_part${idx + 1}.sql`;
    let sql = header(fn, `barangays part ${idx + 1} of 3`);
    sql += `-- Barangays in this chunk: ${chunk.length}\n`;
    sql += batchInsert("ph_barangays", ["code", "city_code", "name"], chunk);
    files.push({ name: fn, sql });
  });

  return files;
}

(async () => {
  const raw = await fetchAll();
  const transformed = transform(raw);
  const files = emit(transformed);
  mkdirSync(OUT_DIR, { recursive: true });
  for (const { name, sql } of files) {
    const path = resolve(OUT_DIR, name);
    writeFileSync(path, sql, "utf8");
    console.log(`Wrote ${name}  (${(sql.length / 1024).toFixed(1)} KB)`);
  }
})();
