-- supabase/migrations/20260502120300_storage_buckets.sql
-- Creates the three private buckets and their storage.objects RLS
-- policies. All buckets are private; clients access via signed URLs
-- generated by the app server.

-- =======================
-- Buckets
-- =======================
INSERT INTO storage.buckets (id, name, public) VALUES
  ('avatars',        'avatars',        false),
  ('thermal-images', 'thermal-images', false),
  ('thermal-csv',    'thermal-csv',    false)
ON CONFLICT (id) DO NOTHING;

-- =======================
-- avatars bucket
-- Path layouts:
--   profiles/{profile_id}/avatar.png
--   clinics/{clinic_id}/avatar.png
-- =======================
CREATE POLICY avatars_read ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'avatars');

CREATE POLICY avatars_write ON storage.objects FOR ALL TO authenticated
  USING (
    bucket_id = 'avatars' AND (
      is_admin()
      OR (
        (storage.foldername(name))[1] = 'profiles'
        AND (storage.foldername(name))[2] = auth.uid()::text
      )
      OR (
        (storage.foldername(name))[1] = 'clinics'
        AND (storage.foldername(name))[2] IN (
          SELECT id::text FROM clinics WHERE owner_profile_id = auth.uid()
        )
      )
    )
  )
  WITH CHECK (
    bucket_id = 'avatars' AND (
      is_admin()
      OR (
        (storage.foldername(name))[1] = 'profiles'
        AND (storage.foldername(name))[2] = auth.uid()::text
      )
      OR (
        (storage.foldername(name))[1] = 'clinics'
        AND (storage.foldername(name))[2] IN (
          SELECT id::text FROM clinics WHERE owner_profile_id = auth.uid()
        )
      )
    )
  );

-- =======================
-- thermal-images bucket
-- Path layout: {session_id}/{foot}/{raw|processed|isolated}.png
-- =======================
CREATE POLICY thermal_images_read ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'thermal-images' AND (
      is_admin()
      OR EXISTS (
        SELECT 1 FROM screening_sessions s
        WHERE s.id::text = (storage.foldername(name))[1]
        AND (
          s.subject_profile_id = auth.uid()
          OR s.operator_id = auth.uid()
          OR (auth_role() = 'clinic' AND s.clinic_id = auth_clinic_id())
        )
      )
    )
  );

CREATE POLICY thermal_images_write ON storage.objects FOR ALL TO authenticated
  USING (
    bucket_id = 'thermal-images' AND (
      is_admin()
      OR EXISTS (
        SELECT 1 FROM screening_sessions s
        WHERE s.id::text = (storage.foldername(name))[1]
        AND (
          s.operator_id = auth.uid()
          OR (auth_role() = 'clinic' AND s.clinic_id = auth_clinic_id())
          OR s.subject_profile_id = auth.uid()
        )
      )
    )
  )
  WITH CHECK (
    bucket_id = 'thermal-images' AND (
      is_admin()
      OR EXISTS (
        SELECT 1 FROM screening_sessions s
        WHERE s.id::text = (storage.foldername(name))[1]
        AND (
          s.operator_id = auth.uid()
          OR (auth_role() = 'clinic' AND s.clinic_id = auth_clinic_id())
          OR s.subject_profile_id = auth.uid()
        )
      )
    )
  );

-- =======================
-- thermal-csv bucket
-- Path layout: {session_id}/{foot}.csv
-- =======================
CREATE POLICY thermal_csv_read ON storage.objects FOR SELECT TO authenticated
  USING (
    bucket_id = 'thermal-csv' AND (
      is_admin()
      OR EXISTS (
        SELECT 1 FROM screening_sessions s
        WHERE s.id::text = (storage.foldername(name))[1]
        AND (
          s.subject_profile_id = auth.uid()
          OR s.operator_id = auth.uid()
          OR (auth_role() = 'clinic' AND s.clinic_id = auth_clinic_id())
        )
      )
    )
  );

CREATE POLICY thermal_csv_write ON storage.objects FOR ALL TO authenticated
  USING (
    bucket_id = 'thermal-csv' AND (
      is_admin()
      OR EXISTS (
        SELECT 1 FROM screening_sessions s
        WHERE s.id::text = (storage.foldername(name))[1]
        AND (
          s.operator_id = auth.uid()
          OR (auth_role() = 'clinic' AND s.clinic_id = auth_clinic_id())
          OR s.subject_profile_id = auth.uid()
        )
      )
    )
  )
  WITH CHECK (
    bucket_id = 'thermal-csv' AND (
      is_admin()
      OR EXISTS (
        SELECT 1 FROM screening_sessions s
        WHERE s.id::text = (storage.foldername(name))[1]
        AND (
          s.operator_id = auth.uid()
          OR (auth_role() = 'clinic' AND s.clinic_id = auth_clinic_id())
          OR s.subject_profile_id = auth.uid()
        )
      )
    )
  );
